Migrate Generally Useful Objects From Alerting (Monitor, Execute, Index)
opensearch-project/common-utils pull request #217
Opened 2022-08-09 23:06 UTC by okram

### Description
Alerting has various POJOs that are useful beyond the boundaries of Alerting. In particular, for this push, Monitor was isolated along with those classes within its referential reach. Furthermore, the actions ExecuteMonitor and IndexMontitor (i.e. Create) were migrated as well.
 
### Issues Resolved
Part 1 in the multipart/multi-repository Security Analytics Plugin Issue #10.

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [O] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

Integration testing was done on MacOSX using a Linked Docker environment.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-10 18:01 UTC, getsaurabh02 requested changes
Thanks @okram for taking a shot on this. While introducing these abstraction for plugin to plugin transport communications lets keep below considerations:

1. Common-utils should only have the (models) PoJos and Action Interfaces required for Transport interactions. 
2.  All execution/business logic including the core artifacts (such as Settings) should continue to be owned by the Alerting Plugin itself.
3. To decouple the object and code dependency - we can take the liberty of introducing new model classes in common-utils and use them in the heavy weight (monolithic) classes in Alerting. Such as Monitor object. Instead of moving the monolithic class directly. 

Since we will need to work towards the right abstraction, do you think can we wait for right it to come in soon - even before we merge this PR into the dev branch? 

In case you think if it's going to take some time and its absolutely necessary to unblock parallel stream of work (in Alerting and SecurityAnalytics), we can do a temp merge in dev branch with a note that this should NOT be merged in mainline.

2022-08-10 22:22 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/resthandler/RestExecuteMonitorAction.kt
> +class RestExecuteMonitorAction : BaseRestHandler() {
Okay. I'll put those back in Alerting.

2022-08-10 22:22 UTC, okram commented on src/main/kotlin/org/opensearch/commons/OpenSearchExtensions.kt
> +fun <T> BackoffPolicy.retry(block: () -> T): T {
So `OpenSearchExtensions.kt` is one of those Kotlin "scripts." I can gut the methods needed and put them with their object and then simply get rid of all the Kotlin "scripts".

2022-08-10 22:24 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/model/LegacyOpenDistroAlertingSettings.kt
> +class LegacyOpenDistroAlertingSettings {
Okay. These settings are refered to in the various classes migrated. How do you recommend these settings be specified?

2022-08-10 22:25 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
> +    val uiMetadata: Map<String, Any>
That' be great if there was a simpler `Monitor`. Most of the code pulled over is becauuse `Monitor` is so beefy. If you can kill some of those fields and still get the functionality you are looking for, that'd be golden.

2022-08-11 18:10 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/resthandler/RestExecuteMonitorAction.kt
> +class RestExecuteMonitorAction : BaseRestHandler() {
Latest push to this PR has the REST handlers removed.

2022-08-11 18:12 UTC, okram commented on src/main/kotlin/org/opensearch/commons/OpenSearchExtensions.kt
> +fun <T> BackoffPolicy.retry(block: () -> T): T {
By removing classes, I was able to remove this method (along with others). I've gutted all unused methods in the Kotlin "scripts" (meta-programming extensions).

2022-08-11 18:12 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/JobScheduler.kt
> +class JobScheduler(private val threadPool: ThreadPool, private val jobRunner: JobRunner) {
Was able to remove `JobRunner`, `JobScheduler`, and `JobSchedulerMetrics`.

2022-08-11 18:14 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/model/Action.kt
> +) : Writeable, ToXContentObject {
I was unable remove `Action`. It's fairly tangled in `Monitor`. Will now do as you recommend with a "mini-Action" implementation.

2022-08-11 18:39 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
> +    val uiMetadata: Map<String, Any>
What are the attributes you believe should be isolated? Only primitives (no objects)?  If so, that would create a cascade of deletes: `Trigger`, `TriggerRunResult`, `Input`, `BuckerLevelTrigger`, `BucketSelector*` (like 5 classes).

If having `Monitor` only contain primitives is legitimate, then tell me and I'll put my hazmat suit back on, pull out my chainsaw, and start butchering away!  <with a crazed grin on my face>

2022-08-15 18:08 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/model/AlertIndices.kt
> +class AlertIndices(
This has been removed.

2022-08-15 18:09 UTC, okram commented on src/main/kotlin/org/opensearch/commons/alerting/model/LegacyOpenDistroAlertingSettings.kt
> +class LegacyOpenDistroAlertingSettings {
There were only a few `DEFAULT` settings that were ultimately referenced in this class. I moved them to `const` in the the respective depending classes. Thus, this has been removed.

2023-01-20 00:22 UTC, lezzago commented
The approach has changed, so closing this PR

2023-01-20 00:22 UTC, closed without merging