Added requestedTenant access info in User model
opensearch-project/common-utils pull request #222
Opened 2022-08-22 19:33 UTC by vamsi-amazon

Signed-off-by: vamsi-amazon <reddyvam@amazon.com>

### Description
Added requestedTenancy access info in User Model.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-22 21:59 UTC, getsaurabh02 reviewed
Which release are planning to release this? Also do we have any backport plans considering this could be a breaking change for the consumer plugins.

2022-08-23 00:30 UTC, vamsi-amazon commented
> Which release are planning to release this? Also do we have any backport plans considering this could be a breaking change for the consumer plugins.

I want to backport to all the versions till 1.3. 

I am not sure of all the consumers of the plugin. If the consumers are creating User then this would cause issues if they don't upgrade because of the changes in constructor. 

Should I keep the old constructor as well? I guess this is the safest way so that whoever is using old constructor would not cause any failures.

2022-08-23 17:26 UTC, dblock commented
> Should I keep the old constructor as well? I guess this is the safest way so that whoever is using old constructor would not cause any failures.

Yes, that's probably the right thing to do.

2022-08-24 21:57 UTC, getsaurabh02 requested changes

2022-08-24 21:57 UTC, getsaurabh02 commented on src/main/java/org/opensearch/commons/authuser/User.java
> +        List<String> customAttNames,
nit: final

2022-08-25 17:46 UTC, getsaurabh02 approved these changes

2022-08-30 17:49 UTC, peternied commented on src/main/java/org/opensearch/commons/authuser/User.java
> +    private final String requestedTenantAccess;
Instead of treating this as a string can we make it an enum?

2023-01-20 00:00 UTC, closed without merging