Fix class loader issue for notifications response
opensearch-project/common-utils pull request #38
Opened 2021-07-14 17:02 UTC by joshuali925

Signed-off-by: Joshua Li <joshuali925@gmail.com>

### Description
fix from @dai-chen:
Recreate the response object from `ActionResponse` as specific notifications response in notifications plugin interface to avoid classloader issue when passing response between plugins
 
### Issues Resolved
#37 
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-07-14 17:19 UTC, dai-chen approved these changes
Thanks for the fix!

2021-07-14 17:43 UTC, dblock reviewed
I love this as a start.

Try to refactor this where you don't need to `override fun onResponse` manually in every instance. 

I think I want to be able to write this:

```java
wrapper.execute(
    SEND_NOTIFICATION_ACTION_TYPE,
    SendNotificationRequest(eventSource, channelMessage, channelIds, threadContext),
    object: SomeNewType<ActionResponse, SendNotificationResponse>
}
```

2021-07-14 17:46 UTC, dblock requested changes
This should be refactored, and definitely needs tests to be merged.

2021-07-14 20:27 UTC, dai-chen commented
> I love this as a start.
> 
> Try to refactor this where you don't need to `override fun onResponse` manually in every instance.
> 
> I think I want to be able to write this:
> 
> ```java
> wrapper.execute(
>     SEND_NOTIFICATION_ACTION_TYPE,
>     SendNotificationRequest(eventSource, channelMessage, channelIds, threadContext),
>     object: SomeNewType<ActionResponse, SendNotificationResponse>
> }
> ```

I was trying to extract a `wrapActionListener` method though had problem with `recreateObject` which requires reified type rather than generic type. Let me give it another try.

2021-07-14 22:15 UTC, dblock commented
@joshuali925 excellent!

Is it worth putting this into a method that takes `DELETE_NOTIFICATION_CONFIG_ACTION_TYPE`, and `DeleteNotificationConfigResponse` or are we trying too hard?

```java
client.execute(
            DELETE_NOTIFICATION_CONFIG_ACTION_TYPE,
            request,
            listener
            wrapActionListener(listener) { response -> recreateObject(response) { DeleteNotificationConfigResponse(it) } }
        )
```

2021-07-14 22:56 UTC, joshuali925 commented
@dblock agree that could look cleaner, but in `sendNotification` the client is wrapped with `SecureClientWrapper` before calling `execute`. I assume we'll need to make this an exception if we generalize the execute function, and i'm not sure if there will be other exceptions in the future. Anyways I'll also defer to @dai-chen since he is coming up with the fixes and refactoring
https://github.com/opensearch-project/common-utils/blob/d5bcf10798632556e548442221e3c42936264273/src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt#L218-L225

2021-07-19 21:48 UTC, dai-chen commented
Closing for https://github.com/opensearch-project/common-utils/pull/40

2021-07-19 21:48 UTC, closed without merging

2021-07-19 21:51 UTC, dai-chen commented
> @dblock agree that could look cleaner, but in `sendNotification` the client is wrapped with `SecureClientWrapper` before calling `execute`. I assume we'll need to make this an exception if we generalize the execute function, and i'm not sure if there will be other exceptions in the future. Anyways I'll also defer to @dai-chen since he is coming up with the fixes and refactoring
> https://github.com/opensearch-project/common-utils/blob/d5bcf10798632556e548442221e3c42936264273/src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt#L218-L225

@joshuali925 @dblock I tried this idea but the code was not clean as I thought. This is mostly because of generic types and number fo params required by each execute call. I would suggest keeping it as is for now.