integrate security-analytics & alerting for correlation engine
opensearch-project/common-utils pull request #412
Opened 2023-04-18 21:47 UTC by sbcd90

### Description
integrate security-analytics & alerting for correlation engine
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-18 21:57 UTC, lezzago requested changes

2023-04-18 21:57 UTC, lezzago commented on src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
> +    const val SUBSCRIBE_FINDINGS_ACTION_NAME = "cluster:admin/opendistro/alerting/findings/subscribe"
rename to `cluster:admin/opensearch/alerting/findings/subscribe`

2023-04-19 01:19 UTC, praveensameneni approved these changes

2023-04-19 01:34 UTC, lezzago approved these changes

2023-04-19 01:35 UTC, merged